import { Song } from "./csv";

export const DEMO_SONGS: Song[] = [
  { title: "Down with the Sickness", artist: "Disturbed", allArtists: ["Disturbed"] },
  { title: "Nothing Else Matters", artist: "Metallica", allArtists: ["Metallica"] },
  { title: "Enter Sandman", artist: "Metallica", allArtists: ["Metallica"] },
  { title: "Bring Me To Life", artist: "Evanescence", allArtists: ["Evanescence"] },
  { title: "Chop Suey!", artist: "System Of A Down", allArtists: ["System Of A Down"] },
  { title: "Duality", artist: "Slipknot", allArtists: ["Slipknot"] },
  { title: "Desire", artist: "Sub Focus", allArtists: ["Sub Focus", "Dimension"] },
  { title: "Afterglow", artist: "Wilkinson", allArtists: ["Wilkinson", "Becky Hill"] },
  { title: "Brand New", artist: "Wilkinson", allArtists: ["Wilkinson"] },
  { title: "Granite", artist: "Pendulum", allArtists: ["Pendulum"] },
  { title: "Witchcraft", artist: "Pendulum", allArtists: ["Pendulum"] },
  { title: "Airplane Mode", artist: "Vibe Chemistry", allArtists: ["Vibe Chemistry"] },
  { title: "Propane Nightmares", artist: "Pendulum", allArtists: ["Pendulum"] },
  { title: "Firestarter", artist: "The Prodigy", allArtists: ["The Prodigy"] },
  { title: "Vivir Mi Vida", artist: "Marc Anthony", allArtists: ["Marc Anthony"] },
  { title: "Ahora Quien", artist: "Marc Anthony", allArtists: ["Marc Anthony"] },
  { title: "Amores Como el Nuestro", artist: "Jerry Rivera", allArtists: ["Jerry Rivera"] },
  { title: "Suavemente", artist: "Elvis Crespo", allArtists: ["Elvis Crespo"] },
  { title: "Bamboléo", artist: "Gipsy Kings", allArtists: ["Gipsy Kings"] },
  { title: "Bésame Mucho", artist: "Andrea Bocelli", allArtists: ["Andrea Bocelli"] },
  { title: "Hurt", artist: "Johnny Cash", allArtists: ["Johnny Cash"] },
  { title: "I Fall In Love Too Easily", artist: "Chet Baker", allArtists: ["Chet Baker"] },
  { title: "Come Fly With Me", artist: "Frank Sinatra", allArtists: ["Frank Sinatra"] },
  { title: "All of Me", artist: "John Legend", allArtists: ["John Legend"] },
  { title: "Stand By Me", artist: "Ben E. King", allArtists: ["Ben E. King"] },
  { title: "I Will Always Love You", artist: "Whitney Houston", allArtists: ["Whitney Houston"] },
  { title: "Stairway to Heaven", artist: "Led Zeppelin", allArtists: ["Led Zeppelin"] },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses", allArtists: ["Guns N' Roses"] },
  { title: "Hotel California", artist: "Rock Masters", allArtists: ["Rock Masters"] },
  { title: "Bonfire", artist: "Knife Party", allArtists: ["Knife Party"] },
  { title: "Internet Friends", artist: "Knife Party", allArtists: ["Knife Party"] },
  { title: "Greyhound", artist: "Swedish House Mafia", allArtists: ["Swedish House Mafia"] },
  { title: "The Business", artist: "Tiësto", allArtists: ["Tiësto"] },
  { title: "Bass Cannon", artist: "Flux Pavilion", allArtists: ["Flux Pavilion"] },
  { title: "Pria", artist: "Charlotte de Witte", allArtists: ["Charlotte de Witte"] },
  { title: "Deutschland", artist: "Rammstein", allArtists: ["Rammstein"] },
  { title: "As The Rush Comes", artist: "Motorcycle", allArtists: ["Motorcycle"] },
  { title: "An Analog Guy in a Digital World", artist: "Martin Roth", allArtists: ["Martin Roth"] },
  { title: "Black Sands", artist: "Bonobo", allArtists: ["Bonobo"] },
  { title: "Jerusalema", artist: "Master KG", allArtists: ["Master KG"] },
  { title: "Wolf Totem", artist: "The HU", allArtists: ["The HU"] },
  { title: "Solovey", artist: "Go_A", allArtists: ["Go_A"] },
  { title: "Chambermaid Swing", artist: "Parov Stelar", allArtists: ["Parov Stelar"] },
  { title: "Lose Control", artist: "MEDUZA", allArtists: ["MEDUZA", "Becky Hill", "Goodboys"] },
  { title: "High Quality Nahui", artist: "Uamee", allArtists: ["Uamee"] },
  { title: "Slav King", artist: "DJ Blyatman", allArtists: ["DJ Blyatman", "Life of Boris"] },
];
